# version: '3'
services:
  mysql:
    image: 'mysql:latest'
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=cart
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_HOST=mysql

  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379
depends_on:
      - mysql